import React from 'react';
import fleekLogo from './fleek-logo.png';
import reactLogo from './react-logo.svg';

import './App.css';

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <img src={reactLogo} className="React-logo" alt="react-logo" />
        <p>
          SKOOMApp deployed on IPFS through Fleek.
        </p>
       <pre>
           NNNNNNNNNNNNNNm/++ys/mNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMNNNNNNNNNNNNNNNNNNNNho+/-:-+mNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNN/.:ohy/yNNNNNNNNNNNNNNNNNNNNNNNNNNNMMMMMMMMNNNNNNNNNNNNNNNNd+-.:-/yssdNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNh:/yy/:osmNNNNNNNNNNNNMMMMMNNNNNMMMMMMMMMMMMMNMMMMMNNNNNNds:..:/+ymNdmNNNMMMMMNMMNNNN
NNNNNNNNNNNNNNNNh+ydoohmmNNNNNNNNNMMMMMMMMNNNMMMMMMMMMMMMMMMMMMMNNNNNNms-`./oydNNNNNNNNMMMMMMMMMMNNN
NNNNNNNNNNNNNNNNNyohhyhmmNNNNNNNNNNNNMMNMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNs.``-+mydNNNNNNNNNNNNMMMMMMNNN
NNNNNNNNNNNNNNNNNNmhdhoyymNdmNNNNNMMMNNNNNNNMMMMMMMMMMMMMMMMMMMMNNNNNy-.-:osmNNNNNNNNNNNNNNMMMMMNNNN
NNNNNNNNNNNNNNNNNNm+d++:/sdh:ymNNNNNNNNNNNNNNNNNNNMMMMMMMMMNNNNNNNNmy:--/shmNNNNNNNNNNNNMMMMMMMMMMNN
NNNNNNNNNNNNNNNNNNysmmd+y+/y/.+mNNNNNNNNNNNNNNNNNMMMMMNNNNNNNNNNNNd/:--./dNNNNNNNNNNNNNNMMMMMMMMMNNN
NNNMMMMMNNNNNNNNNNyhmdNNmo/+s.`oNNNNNNNNNNNNNNNMMMMMMMNNNNNNNNNNNd:-/:.:sNNNNNNNNNNNNNNNNMMMMMMMMNNN
NNNMMMMMMMNNNNNNNNdysymNNds+h/..sNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNd:-::-/hmNNNNNNNNNNNNNNNNMMMMMNNNNNN
NMMMMMMMMMNNNNNNNNNdssdNNNmyys-..omNNNNNNNNNNNNNNNNNNNNNNNNNNNNm:.-::-+dmmmNNNNNNNNNNNNNNMMMMMNNNNNN
NMMMMMMMMMNNNNNNNNNNNdsdNNdho+:...yNNNNNNNNNNNNNNNNNNNNNNNNNNNm+.--:-:++dysNNNNNNNNNNNNNMMMMMNNNNNNN
NMMMMMMMMMNNNNNNNNNNNNd+ydyhys+-``/NNNNNNNNNNNNNNNNNNNNNNNNNNNo-....-::oh-dNNNNNNNNNNNNNNNNNNNNNNNNN
NNNMMMMMMNNNNNNNNNNNNNNd+ydhhhy:.`.dNNNNNNNNNNNNNNNNNNNNNNNNNm+----``-ym/yNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNMMMNNNNNNNNNNNNNNNmoyhyhd+.`.dNNNNNNNNNNNNNNNNNNNNNNNNNd+-/+/...y+hNmmmmNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNmohdhhs-..dNNNNNNNNNNNNNNNNNNNNNNNNds/+hho:...yNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNm+hyys/-.+NNNNNNNNNNNNNNNNNNNNNNmN+:sdmd+/-/:hNmNmNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNyossy/..:mdmNNNNNNNNNNNNNNNNNNmhy::hmho::+++dmNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNooyo+-.-hhdNNNNNNNNNNNNNNNNNNd/o///::::/:-omNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNd:shy:--+osmNNNNNNNNNNNNNNNNmo-::--.-:+:.+hNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNMMMMMMMMNNNNNNNNNNNNNNNN+sdd/-:+/+yNNNNNNNNNNNNNNNNs-..`--::::-:mNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNMMMMMMMMMNNNNMNNNNNNNNNh/dmy-:++//odNNNNNNmmNNNNNh/.``./++-.:o/NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNMMMMMMMMMMMMMMMMMMMNNNNNNm/dmmo:/o/:-:sdmNNhyyydNNmo-..-+ymo::om/NmNNNNNNNNNNNNNNNNNNMMMMNNNNNNN
NNNMMMMMMMMMMMMMMMMMMMMMNNNNNN/+dmdsoso/--:+dNm+/o+hmms/-../ydds+/sd:dmNNNNNNNNNNMMMNNMMMMMMMMMMNNNN
NNNMMMMMMMMMMMMMMMMMMMMMNNNNNNs/hNNNmmy+---:yNNh/:omms/:..-/syso++++-hNNNMMMMMMMMMMMMMMMMMMMMMMMNNNN
NNMMMMMMMMMMMMMMMMMMMMMMMNNNmdysmNNNmhms/:--/+hms:ydh:::..--:-/os/:--hNNMMMMMMMMMMMMMMMMMMMMMMMMMNNN
NNMMMMMMMMMMMMMMMMMMMMMMMNNdss/sNmyy//o///:::.+mdoo/-..-```````.:+/::NNNNMMMMMMMMMMMMMMMMMMMMMMMMNNN
NNNMMMMMMMMMMMMMMMMMMMMMNNy--.-:yo//:.-+syo+/:-so:-.``.`...`````.++-oNNNNMMNNMMMMMMMMMMMMMMMMMMNNNNN
NNNNMMMMMMMMMMMMMMMMMMNNNm/.`..-/:/+/-/y//+/o+------:/::/+/--///:/o:yNNNNNMNNMMMMMMMMMMMMMMMMMNNNNNN
NNNNNMMMMMMMMMMMMMMMNNNNNm+:+.-/+/-..::hs:+yhyyhhshhmmdds+:------+o/osyymNNNMMMMMMMMMMMMMMMMMMMNNNNN
NNNNMMMMMMMMMMMMMMMMNNNNNNy--.//::-..-:sy/smmmNmmmmmmmNNds/::---/so+/-..yNNNMMMMMMMMMMMMMMMMMMNNNNNN
NNNNMMMMMMMMMMMMMMMMNNNNNNy-..//:::---::o++so://+syo/:/oyhsoo///+so++:-:dNNNMMMMMMMMMMMMMMMMMMNNNNNN
NNNNMMMMMMMMMMMMMMMMMNNNNy+:..:::/:-----::::-.-:/:/:--::///////+yy/-+/-:yNNNNMMMMMMMMMMMMMMMMMNNNNNN
NNNMMMMMMMMMMMMMMMMMMNNNm+::-..----.....---::.--o:/+--/++:-..:oyys+/+/::+NNNNNMMMMMMMMMMMMMMMNNNNNNN
NNNMMMMMMMMMMMMMMMMMNNNNd/+:::.:+oooo/-.-:///---/:::..-///:---+hdhs+/:+::NNNNNNMMMMMMMMMMMMMNNNNNNNN
NNNMMMMMMMMMMMMMMMMMNNNNNyys--ohmNNNNNmhysoso--//::....-::::://+yo:--::--hNNNNNMMMMMMMMMMMMMMNNNNNNN
NNNMMMMMMMMMMMMMMMMMNNNNNNd/:hmNms+//+sdmNmmy-.-:-.`.:shdho/::-:oyo:-//+:yNNNNMMMMMMMMMMMMMMMNNNNNNN
NNNMMMMMMMMMMMMMMMMMMNNNNhy-yohy:.`....-/sdd/------../dh+:-..````:hd//shohNNNNMMMMMMMMMMMMMMMMNNNNNN
NNNMMMMMMMMMMMMMMMMMMMNNmho+shN+.``...---::++:----..:+/:------.``-hm+///+mNNNMMMMMMMMMMMMMMMMMNNNNNN
NNNMMMMMMMMMMMMMMMMMMMNmdso+/+md:-..----::::/:.---..:+:::::------/dyooo/+NNNNNNMMMMMMMMMMMMMMMNNNNNN
NNNMMMMMMMMMMMMMMMMMMMNNyoo::-+yhs///+//oyss+:-:----/yysso//:::+yho+sh+:yNNNNMMMMMMMMMMMMMMMMMMNNNNN
NNNNMMMMMMMMMMMMMMMMMNNNdyhy+s+:://oyhhhhhhhso/:--.:+oyyss+:/+sso-..-///dNNNMMNMMMMMMMMMMMMMMMMNNNNN
NNNNNMMMMMMMMMMMMMMMMNNNNddmmNNmdhyhy+++-:+/-..`````.-::-..-.``-:/:-`-hhNNNNMMMMMMMMMMMMMMMMMMMNNNNN
NNNNNMMMMMMMMMMMMMMMMNNNNNmNdNmo:---/so+/--:/sy+:.:os+/--:/hdshd+s-``.odNNNNMMMMMMMMMMMMMMMMMMMNNNNN
NNNNNMMMMMMMMMMMMMMMMNNNNNhmNNds+-.:/:------oddh+:oyho/--.-dNNNh/so-./dmNNNNNMNMMMMMMMMMMMMMMMNNNNNN
NNNNNMMMMMMMMMMMMMMMMMNNNNdNNms:o...--:.----://+/.::--..---sNNm/:+s/``yNNNNNNNNNMMMMMMMMMMMMMNNNNNNN
NNNNNMMMMMMMMMMMMMMMMMMNNNNNNmo+y-.--:...-:-.`.--..``..--.-.hNh+/+y+.-mNNNNNNNNNMMMMMMMMMMMMMMMMMMNN
NNNNMMMMMMMMMMMMMMMMMMMMNNNNNNdsh/-://-...-:/:/hhhy/:/:-...-yNhs/o+-.hNNNNNNNNNMMMMMMMMMMMMMMNMMMNNN
NNMMMMMMMMMMMMMMMMMMMMMMMNNmhmNdy:.-+hy-.`::-/+://:/-./:`-:yNNsso+:.oNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMN
MMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNmh+/smmo//o-`..`..`--./o:smNNh+/+shhNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMNN
MMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNdm+/+syyhmm:-:-.:/:oyoymdmhhmo+::+NNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMNNN
MMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNh+sohmds+smh++++/shddhmNNms/sdho//oNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMNN
MMMMMMMMMMMMMMMMMMMMMMMMMMMNNNd+::ymNNNd////shhddmNdddho/ohmNNhdhdNNNMNNNNMMMMMMMMMMMMMMMMMMMMMMMMMN
MMMMMMMMMMMMMMMMMMMMMMMMMMMNNmhsoodNNmNNms/--/oo+sss+:-+dNNNNNNNNNNNNNMMMMMMMMMMMMMMNNNMMMMMMMMMMMMN
MMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNmmNNNNNNNNmhs///////oydNNNNNNNNNNNNNNNMMMMMMMNMMMMMMNNNMMMMMMMMMMMMN
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMNhsoosymMMMdssMMMMNssyMMMMmyoooyNMMMMMMmyoooymMMMMmssdMMMMMMyssMMMMMMMysmMMMMMMMMMMMMMM
MMMMMMMMMMMMs``-//:.`hMMs `MMMh. /NMMN/``:/-``+MMMN/``:/-``+MMMy  `mMMMMy   NMMMMMh  -NMMMMMMMMMMMMM
MMMMMMMMMMMM` oMMMMNmMMMs `MNo`.yMMMMo `mMMMd` sMMo `dMMMd` sMMy   :MMMm`   NMMMMm. - +MMMMMMMMMMMMM
MMMMMMMMMMMM: .+sydmMMMMs `d: `dMMMMM: -MMMMM. +MM/ -MMMMM. +MMy `/ sMM: o  NMMMM: +m` hMMMMMMMMMMMM
MMMMMMMMMMMMNy+:--.`-hMMs  `.. :mMMMM: -MMMMM. +MM: -MMMMM. +MMy .N.`do +d  NMMMo .NMy .mMMMMMMMMMMM
MMMMMMMMMMMMMMMMNNm/ .MMs  /mm: -dMMM/ -MMMMN` +MM/ .MMMMM. +MMy .Mh`.`-Nd  NMMd` -///` :MMMMMMMMMMM
MMMMMMMMMMMm:+hdddy- :MMs `NMMN/ .hMMh` /hdh/ .dMMd` /hdh/ `dMMy .MMo..dMd  NMN. :ooooo` oMMMMMMMMMM
MMMMMMMMMMMmo:.....:sNMMy.-MMMMN+.-dMMd+-...-+mMMMMd+-...-+mMMMh.:MMMmmMMm..NMo.:NMMMMMy.-mMMMMMMMMM
MMMMMMMMMMMMMMNmmmNMMMMMNNNMMMMMMNNNMMMMNmmmMMMMMMMMMNmmmNMMMMMMNNMMMMMMMMNNMMNNNMMMMMMMNNNMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
       </pre>
      </header>
    </div>
  );
}

export default App;
