import React from 'react';
import fleekLogo from './fleek-logo.png';
import reactLogo from './react-logo.svg';

import './App.css';

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <img src={reactLogo} className="React-logo" alt="react-logo" />
        <p>
          SKOOMApp deployed on IPFS through Fleek.
        </p>
       <pre style={{whitespace:'normal'}}>

MMMMMMMMMN-/y+mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNs/--:dMMMMMMMMMM
MMMMMMMMMM+/h+/hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNy-`-/dNmMMMMMMMMMM
MMMMMMMMMMNoyyyNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm-`-yhMMMMMMMMMMMMMM
MMMMMMMMMMMNddsydMdMMMMMMMMMMMMMMMMMMMMMMMMMMN:`-omNMMMMMMMMMMMMMM
MMMMMMMMMMMMsmy:oso/mMMMMMMMMMMMMMMMMMMMMMMMh:.-yNMMMMMMMMMMMMMMMM
MMMMMMMMMMMMyNNNd:s.:NMMMMMMMMMMMMMMMMMMMMMs--./NMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMmohMMhy+`:mMMMMMMMMMMMMMMMMMMMs.-.+NNMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMNdhNmy+. /MMMMMMMMMMMMMMMMMMh``.-:ysmMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMysddh/``mMMMMMMMMMMMMMMMMN:`.``+yoMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMdyddy` mMMMMMMMMMMMMMMMMd:/+.`+yNNNNMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMhyhh-`yMMMMMMMMMMMMMMMm/smy:--NMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMssy:`/mNMMMMMMMMMMMMho:ys:-:+NMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMm/hs`-shMMMMMMMMMMMm-:...-:.hMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMohm--+/hNMMMMMMMMN/``.-.--sMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMdsNy-+:-+dNMdhhMNy.`-sh-:hsNMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMN:dNdho-.:dN+/oNh:``/dy++s+NMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMNmoNMNdd/../ym:hh-. `--/o/-+MMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMm/::ho/-:++/--d+:` `     .+-hMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMM/``./:/.+o//o---::/:/-`---+:dNNMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMs:./:-`.:h:hmmmmmNNNy:..`-s//:oMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMy``:.-..-//o/:/os/:+yso/:os//.+MMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMh:-`..-.``..-.`-::-./:.`-oho:+.-MMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMs+:.:syys/-:/-`-/-``--.`.ody+-:.dMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMm-yNmyoshNmds..-``:oyo/::oo.-::yMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMNoood. ```-+h:...`.os-.``  +m:oodMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMNy++oN:``..---:...`-/--...`.od++:NMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMNhy://o/+ssyhho:--./yhy+:/+y+:o/+MMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMNmmNmyosso/:+-.````-:.--.-::``sdMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMmNMy:`-/:-..ods-oh+-..mmN+o`.sNMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMNMN++`......-/+.--.`..hMh:s/`yMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMNsy..:``.-.-oo/.-.``:My:o--NMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMmNNh-:ys.`:./::-.`:./dNs++-dMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMmy/shsh+..`--+/hhmmh/-hNMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMd+shmhoh++oodmdNmy+ddo+dMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMNy+yMNMmo:/ssyhs++hNMMNNNMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMNMMMMMNmyssosydNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMd+//+sNM++MMd/sMMh+//+hMMNs///omMM:/NMMM+:mMMMm:yMMMMMMMMM
MMMMMMMN`:dmdhMM--No.sMMd +mmo dM+`hmd--MM  /MMo` dMMN--`mMMMMMMMM
MMMMMMMM+-/++yMM-.:`:NMMy dMMd sM-.MMM/ MM /.sd`o dMM+.N:-NMMMMMMM
MMMMMMMMNNmds yM-`sd.:NMy yMMh yM:.NMN:`MM oh`.sh dMy -+/ +MMMMMMM
MMMMMMMm:/++:-mM::MMm-:NN+.//./NMd-:/:.yMM`sMysMh`mm.+ddds`hMMMMMM
MMMMMMMMMNmmNMMMNNMMMNmNMMNmmNMMMMMNdmMMMMmNMMMMNmMNmMMMMMmNMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
       </pre>
      </header>
    </div>
  );
}

export default App;
